name: React Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        working-directory: ./react-blog
        run: npm install

      - name: Run Tests
        working-directory: ./react-blog
        run: npm run test
